pure_pursuit_controller:
  ros__parameters:
    lookahead_distance: 0.3
    linear_velocity: 0.8
    max_angular_velocity: 1.2
    goal_tolerance: 0.15
    min_lookahead_distance: 0.2
    max_lookahead_distance: 0.4
    steering_gain: 1.2
