trajectory_generator:
  ros__parameters:
    waypoints_file: "waypoints.yaml"
    bspline_degree: 3
    bspline_samples: 300
    control_point_spacing: 0.15
    control_point_multiplier: 4
    max_velocity: 0.2
    min_velocity: 0.05
    max_acceleration: 0.5
    max_jerk: 0.5
    sampling_interval: 0.05 