waypoints:

  - x: 0.0
    y: 0.0

  - x: 1.2
    y: 2.5

  - x: 2.8
    y: 1.7

  - x: 3.5
    y: -1.2

  - x: 4.1
    y: 0.8

  - x: 5.0
    y: 2.2

  - x: 5.8
    y: -0.5

  - x: 6.4
    y: 1.9

  - x: 7.2
    y: 0.3

  - x: 8.0
    y: 1.0
  